export const recibir = [
  'Buiiiiii',
  'Tuve examen hoy',
  'Pa q mierda cara 130 bajas entre ayer y hoy',
  'Tire tiro hoy',
  'Hola',
  'Hola amigo',
  '🤗',
  'Cristal Narvaja',
  'Pa jodido bode',
  'Juajuajuajua',
  'La vip',
  'Rober Prates',
  'Q hay',
  'Que hacen',
  'No tengo amigos',
  'Hoy salí, fui a xxx',
  'Mamá me compró una bermuda hoy',
  'Pa buenisimo',
  'Buen dia',
  'Tire tiro soy gangster',
  'Bueno quien es gangster y quien es loke',
  'La cogo',
  '👀',
  'Toy xico',
  'Ta callate mierda',
  'Extraño a toselin 😩😭😭',
  'Buiiii bela',
  'Pa cara como la gente queda loke andando en moto eléctrica lpm',
  'U forulo',
  'Cual es la movida',
  'Hola q hay',
  'Pa cara manejar de beke es horrible',
  'Prefiero manejar empedo y n de beke',
  'Buen dia perros',
  'Impecable',
  'Hola gordo culo de manati',
  'Bueno y q hsy',
  'Siesta bien tranqui',
  'Se ta armando lluvia en la ciudad de Montevideo',
  'Pa los safrales asquerosos ya estan rampando',
  'Tuve 3 examenes hoy',
  'Solo mumu quiere el mugriento',
  'Culito foca y compania',
  'A mira quien apareció',
  'Derecho procesal penal ahora dentro de 1h',
  'Salve tiro un exito',
  'Hay q cagarlos a palo',
  'Se termino el recreo',
  'Aguante Manini carajo',
  'Los mafia culo de foca',
  'Eran solo bunda del FA',
  'El munino taba',
  'N consigo dormir cara nose',
  'Yo toy estudiando 2 examenes mañana',
  'Anda estudiar muchacho',
  'Aca andamos activos',
  'Y',
  'Quien ta gangster quien se muda al munino??',
  'Malditos vagos al cuartel iran',
  'Malditos vagos mantenidos',
  'Juegan por quién se rasca mas las bola',
  'Mira que van a sacar el mides',
  'Maldito pecador',
  'Tengo q ir a declarar lpm',
  '12 tengo audiencia',
  'El chino es el cara',
  'Es verdad canto el himno de los bomberos con orgullo',
  'Años espere este momento',
  'Odio a los milico',
  'Pa que legal meu',
  'Jajajajajaja',
  'Tata anda fumar un beke en la plaza aprovecha q queda poco esa joda',
  'Julio tiene todo empeñado por tu culpa maldito comunista',
  'Papa y julio deberían de andar en hilux con lo q an gastado con el bundon',
  'Callate puto chupasangre de los boninos',
  'Me voy a casar sere deueño de un taller y sere bombero',
  'Mama se va para mallorca mandara los euros 😎',
  'Mama me ama',
  'Extraño mi vieja',
  'Q delicia',
  'Le damo agua y merca por 4 dia',
  'Toy aca metiendo',
  'Mañana asadito en la vip',
  'El unico q va bajar aca sos vos de una trompada q te voy a dar culo de muzzarela',
  'Pa de cara con los fiscales mañana',
  'Juajuajuajaujaujau cara q legal',
  'Jajajaja al munino le encanta',
  'Q fdp',
  'Hice video llamada con el culo de hipopótamo y n le atendió',
  'Pa'
];

export const enviar = [
  'Y loke',
  'Ah mira',
  'Ta callate la boca',
  'Anda a estudiar',
  'Cara que mierda me importa eso?',
  'Jajajajajajajaj',
  'En la buena?',
  'No te pregunté nada',
  'Alcahuete de los bombero',
  'Cara tenes 40 años y no sabes salir solo porque te perdes',
  'Juajuajauaj',
  'Y negro? Que hay?',
  'Mmmm..',
  'Ok',
  'Pa ahora no puedo, mas tarde hablamos'
];